### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by GirkovArpa** [autophytes/jotling#10]
I ran the executable installer from the Releases and it stayed stuck on the splash screen.  The menu option for creating a new project doesn't do anything.

**Comment by autophytes** [comment]
Thanks for letting me know! The releases aren't really being maintained just yet, but I ran a new build in case the one that you downloaded had a bug in it I didn't realize. I'll definitely be giving Windows some love in the future (and styling refinements - I'm developing on a Mac so I don't see it on Windows often), but for now I'm just hammering out features. I appreciate you telling me you had an issue with it!
